config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :companies do
    resources :complaints, only: :create
  end
  root 'companies#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :complaints, dependent: :destroy
  validates :name, presence: true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :company
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :complaints
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: :index

  def index
    @companies = Company.order('id DESC')
  end

  def new
    @company = Company.new
    respond_to :js
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      respond_to :js
    else
      redirect_to root_path, alert: 'There was an error, please try again.'
    end
  end

  def show
    @complaint = Complaint.new
    @complaints = @company.complaints.order('created_at DESC')
    respond_to :js
  end

  def edit
    respond_to :js
  end

  def update
    if @company.update(company_params)
      respond_to :js
    else
      redirect_to root_path, alert: 'There was an error, please try again.'
    end
  end

  def destroy
    @company.destroy
    respond_to :js
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end

  def set_company
    @company = Company.find(params[:id])
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  def create
    @complaint = Complaint.new(
      user: current_user,
      company_id: params[:company_id],
      content: params[:complaint][:content]
    )
    if @complaint.save
      respond_to :js
    else
      redirect_to root_path, alert: 'There was a mistake, please try again.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/companies/_company.html.erb
<div id="<%= company.id %>" class="card mt-3">
  <div class="card-body d-flex justify-content-between">
    <%= company.name %>
    <div class="actions">
      <% if user_signed_in? %>
        <%= link_to 'Detail', company_path(company), class: 'btn btn-info btn-sm', data: { remote: true } %>
        <%= link_to 'Edit', edit_company_path(company), class: 'btn btn-secondary btn-sm', data: { remote: true } %>
        <%= link_to 'Delete', company_path(company), class: 'btn btn-danger btn-sm', data: { remote: true, method: :delete} %>
      <% end %>
    </div>
  </div>
</div>

app/views/companies/create.js.erb
$('.companies-container').prepend('<%= j render @company %>');
$('.modal').modal('hide');

app/views/companies/destroy.js.erb
$('#<%= @company.id %>').hide(300);

app/views/companies/edit.js.erb
$('.modal-title').text('Edit company:');
$('.modal-body').html('<%= j render 'shared/form', company: @company %>');
$('.modal').modal('show');

app/views/companies/index.html.erb
<div class="companies-container">
  <%= render @companies %>
</div>

<%= render 'shared/modal' %>

app/views/companies/new.js.erb
$('.modal-title').text('Enter new company:');
$('.modal-body').html('<%= j render 'shared/form', company: @company %>');
$('.modal').modal('show');

app/views/companies/show.js.erb
$('.modal-title').text('<%= @company.name %>');
$('.modal-body').html('<%= j render 'shared/complaints_form', {complaint: @complaint, company: @company} %>');
$('.modal-footer').html('<%= j render @complaints %>');
$('.modal').modal('show');

app/views/companies/update.js.erb
$('#<%= @company.id %>').replaceWith('<%= j render @company %>');
$('.modal').modal('hide');

app/views/complaints/_complaint.html.erb
<div class="card mt-2">
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= complaint.content %></p>
      <footer class="blockquote-footer"><%= complaint.user.name %></footer>
    </blockquote>
  </div>
</div>

app/views/complaints/create.js.erb
$('.modal-footer').prepend('<%= j render @complaint %>');
$('#complaint_content').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompaniesMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <% if notice.present? %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      
      <% if alert.present? %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_complaints_form.html.erb
<%= form_with(model: [company, complaint]) do |f| %>
  <div class="form-group">
    <%= f.label :content, 'Would you like to say something?' %>
    <%= f.text_area :content, class: 'form-control', placeholder: 'Leave your complaint here...' %>
  </div>
  <%= f.submit 'Send', class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: company) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <%# title %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%# content %>
      </div>
      <div class="modal-footer d-block">
        <%# content %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Complaints</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <%= link_to 'New company', new_company_path, class: 'nav-link', data: { remote: true } %>
        <li>
          <div class="dropdown">
            <a href="#" class="nav-link dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </div>
          </div>
        </li>
      <% else %>
        <li><%= link_to 'Log in', new_user_session_path, class: 'nav-link ml-3' %></li>
        <li><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>